# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1icMD6HeC4iDPgZMnx24yG9yKRla7FNMl
"""

num1 = int(input("enter first number \n"))
num2 = int(input("enter second number \n"))
print("add:", num1+num2)
print("sub:", num1+num2)
print("div:", num1/num2)
print("mul:", num1*num2)
print("floordiv:", num1//num2)
print("exp:", num1**num2)
print("mod:",num1 % num2)

