# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1icMD6HeC4iDPgZMnx24yG9yKRla7FNMl
"""

# 1. Show Co-relation using HeatMap
# Import libraries and dataset
import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns
car_df = pd.read_csv("/content/CarPrice_Assignment.csv")
# Create co-relation
filtered_df = car_df.select_dtypes(['int64', 'float64'])
correlation_matrix = filtered_df.corr()
correlation_matrix
# Create the heatmap
plt.figure(figsize = (12,8))
plt.rcParams.update({'font.size': 10})
sns.heatmap(correlation_matrix, cmap = 'vlag', vmin=-1, vmax=1, annot=True, fmt=".2f",
square=True, linewidths=.50)
plt.show()

