# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1icMD6HeC4iDPgZMnx24yG9yKRla7FNMl
"""

#List Operations
my_list = [10, 20, 25, 30, 40, 50]
# Append
my_list.append(60)
print("After append:", my_list)
# Clear
my_list.clear()
print("After clear:", my_list)
# Copy
my_list = [10, 25, 20, 30, 40, 50]
copy_of_my_list = my_list.copy()
print("Copy of list:", copy_of_my_list)
# Pop
last_item = my_list.pop()
print("Popped item:", last_item)
print("After pop:", my_list)
# Remove
my_list.remove(25)
print("After remove:", my_list)

#Tuple Operations
Tuple1 = ('a', 'b', 'c', 'd')
Tuple2 = ('e', 'f', 'g', 'h')
# Repetition
repeated_Tuple1 = Tuple1 * 2
print("Repeated Tuple1:", repeated_Tuple1)
# Concatenation
concatenated_Tuples = Tuple1 + Tuple2
print("Concatenated Tuple1 and Tuple2:", concatenated_Tuples)
# Membership
is_a_in_Tuple1 = 'a' in Tuple1
print("Is 'a' in Tuple1?", is_a_in_Tuple1)
# Iteration
print("Iterating over Tuple1:")
for item in Tuple1:
  print(item)

#Set Operations
Set1 = {1, 4, 2, 4, 5, 6, 3, 5, 4, 6, 77, 8, 7, 7, 876}
Set2 = {3, 432, 5, 6, 4, 6, 7, 6, 5, 6, 54, 567, 5}
# Union
union_Set1_Set2 = Set1 | Set2
print("Union of Set1 and Set2:", union_Set1_Set2)
# Intersection
intersection_Set1_Set2 = Set1 & Set2
print("Intersection of Set1 and Set2:", intersection_Set1_Set2)
# Difference
difference_Set1_Set2 = Set1 - Set2
print("Difference of Set1 and Set2 (Set1 - Set2):", difference_Set1_Set2)
# Symmetric difference
symmetric_difference_Set1_Set2 = Set1 ^ Set2
print("Symmetric Difference of Set1 and Set2:", symmetric_difference_Set1_Set2)

#Dictionary Operations
dict = {'Name': 'Hello', 'Age': 22}
# Length
length_given_dict = len(dict)
print("Length of Given Dictionary:", length_given_dict)
# String
string_given_dict = str(dict)
print("String representation of Given Dictionary:", string_given_dict)
dictionaries = {0:" Data",1: "GREAT", 2: "LEARNING",3:"Python",4:"Happy"}
# Copy
copied_dictionaries = dictionaries.copy()
print("Copied Given Dictionary:", copied_dictionaries)
# Key
keys = ['a', 'b', 'c']
new_dict = dict.fromkeys(keys, "Default Value")
print("New Dictionary from Keys:", new_dict)
# Dict Value
values_given = dictionaries.values()
print("Values in Given Dictionary:", list(values_given))

