# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1icMD6HeC4iDPgZMnx24yG9yKRla7FNMl
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

# Ignore warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Load dataset
df = pd.read_csv("/content/bank_csv.csv")

# Drop the first column
df = df.drop(df.columns[0], axis=1)

# Check and clean age column
df['age'] = pd.to_numeric(df['age'], errors='coerce')
df = df[df['age'].notnull()]

# Create age bins
bins = [18, 28, 38, 48, 58, 68, 78, 88]
labels = ['18-28', '28-38', '38-48', '48-58', '58-68', '68-78', '78-87']
df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels, include_lowest=True)

# Group and count
result = df.groupby('age_group')['age'].count().reset_index()
result.rename(columns={'age': 'count'}, inplace=True)

# Print result
print(result.to_string(index=False))

df.groupby('job').agg(Total_Job=('job', 'count')).head()

df.groupby(['age_group','job']).agg({'job':'count', 'marital':'count'}).sort_index(ascending=True)

df[df['job'] == 'unemployed'].groupby('marital').agg(Total_No=('job', 'count'))

df.groupby(['marital', 'job']).agg(Total_No=('job', 'count')).sort_values(ascending=False,
by='Total_No').head()

df.groupby(["education", "job"]).agg(Count=("education", "count")).sort_values(by="Count",
ascending=False).head(5)

df.groupby(["job", "default"]).agg(total_no=('age', 'count')).sort_values(by=['default', 'total_no'],
ascending=False ).head()

