# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1icMD6HeC4iDPgZMnx24yG9yKRla7FNMl
"""

import pandas as pd, seaborn as sns
from scipy.stats import ttest_ind, ttest_1samp
df = pd.read_csv("/content/Crop_recommendation.csv")
# A. Two-Sample T-Test for Temperature and Humidity
rice = df[df['label'] == 'rice']
jute = df[df['label'] == 'jute']
banana = df[df['label'] == 'banana']
grapes = df[df['label'] == 'grapes']
# 1. Rice and Jute
t_temp_rice_jute, p_temp_rice_jute = ttest_ind(rice['temperature'], jute['temperature'],
equal_var=False)
t_humid_rice_jute, p_humid_rice_jute = ttest_ind(rice['humidity'], jute['humidity'], equal_var=False)
# 2. Banana and Grapes
t_temp_banana_grapes, p_temp_banana_grapes = ttest_ind(banana['temperature'],
grapes['temperature'], equal_var=False)
t_humid_banana_grapes, p_humid_banana_grapes = ttest_ind(banana['humidity'], grapes['humidity'],
equal_var=False)

# B. One-Sample T-Test for pH of Mango
mango = df[df['label'] == 'mango']
t_ph_mango, p_ph_mango = ttest_1samp(mango['ph'], 7.5)

print("A. Two-Sample T-Test Results")
print("Rice vs Jute (Temperature): t-stat =", t_temp_rice_jute, "p-value =", p_temp_rice_jute)
print("Rice vs Jute (Humidity): t-stat =", t_humid_rice_jute, "p-value =", p_humid_rice_jute)
36
print("Banana vs Grapes (Temperature): t-stat =", t_temp_banana_grapes, "p-value =",
p_temp_banana_grapes)
print("Banana vs Grapes (Humidity): t-stat =", t_humid_banana_grapes, "p-value =",
p_humid_banana_grapes)

print("\nB. One-Sample T-Test for Mango pH")
print("Mango (pH): t-stat =", t_ph_mango, "p-value =", p_ph_mango)

#1. Rice vs Jute (Temperature and Humidity)
print("Hypothesis Testing for Rice vs Jute (Temperature):")
print("Null Hypothesis (H0): The mean temperature of rice and jute are the same.")
print("Alternative Hypothesis (H1): The mean temperature of rice and jute are different.")
print("\nHypothesis Testing for Rice vs Jute (Humidity):")
print("Null Hypothesis (H0): The mean humidity of rice and jute are the same.")
print("Alternative Hypothesis (H1): The mean humidity of rice and jute are different.")

#2. Banana vs Grapes (Temperature and Humidity)
print("Hypothesis Testing for Banana vs Grapes (Temperature):")
print("Null Hypothesis (H0): The mean temperature of banana and grapes are the same.")
print("Alternative Hypothesis (H1): The mean temperature of banana and grapes are different.")
print("\nHypothesis Testing for Banana vs Grapes (Humidity):")
print("Null Hypothesis (H0): The mean humidity of banana and grapes are the same.")
print("Alternative Hypothesis (H1): The mean humidity of banana and grapes are different.")

# Mango (pH)
print("\nHypothesis Testing for Mango pH:")
print("Null Hypothesis (H0): The mean pH of mango is 7.5.")
print("Alternative Hypothesis (H1): The mean pH of mango is not equal to 7.5.")

#Inferences
#1) Inference based on Temperature
if p_temp_rice_jute < 0.05:
  print("Inference: Reject the Null Hypothesis. The mean temperature of rice and jute are significantly different.")
else:
  print("Inference: Fail to reject the Null Hypothesis. There is no significant difference in temperature between rice and jute.")

#2) Inference based on Humidity
if p_humid_rice_jute < 0.05:
  print("Inference: Reject the Null Hypothesis. The mean humidity of rice and jute are significantly different.")
else:
  print("Inference: Fail to reject the Null Hypothesis. There is no significant difference in humidity between rice and jute.")

#2) Banana vs Grapes
##1) Inference based on Temperature
if p_temp_banana_grapes < 0.05:
  print("Inference: Reject the Null Hypothesis. The mean temperature of banana and grapes are significantly different.")
else:
  print("Inference: Fail to reject the Null Hypothesis. There is no significant difference in temperature between banana and grapes.")

#2) Inference based on Humidity
if p_humid_banana_grapes < 0.05:
  print("Inference: Reject the null hypothesis. The humidity requirements of banana and grapes are significantly different.")
else:
  print("Inference: Fail to reject the null hypothesis. The humidity requirements of banana and grapes are not significantly different.")

# Inference based on p-value
if p_ph_mango < 0.05:
  print("Inference: Reject the Null Hypothesis. The pH of mango is significantly different from 7.5.")
else:
  print("Inference: Fail to reject the Null Hypothesis. The pH of mango is not significantly different from 7.5.")

