# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1icMD6HeC4iDPgZMnx24yG9yKRla7FNMl
"""

import pandas as pd

# Load dataset with correct file path format
df = pd.read_csv("/content/youtube.csv")  # Use 'r' or '\\'

# Convert 'Subscriptions' to numeric
df["Subscriptions"] = pd.to_numeric(df["Subscriptions"].str.extract(r'(\d+)')[0], errors='coerce')

# Convert 'Uploads' to numeric (removes commas)
df["Uploads"] = pd.to_numeric(df["Uploads"].str.replace(',', '', regex=True), errors='coerce')

# Convert 'Views' to numeric (handling commas and missing values correctly)
df["Views"] = (
    df["Views"]
    .str.replace(",", "", regex=True)  # Remove commas
    .replace("--", None)  # Convert "--" to None
    .replace("", None)  # Convert empty strings to None
    .astype("Int64")  # Convert to nullable integer type
)

# Print corrected datatypes
print(df.dtypes)

df[(df['Ch_name'] == 'T-Series') | (df['Ch_name'] == 'SAB TV') | (df['Ch_name'] == 'Zee TV')]

df.groupby(['Ch_name','Subscriptions', 'Views']).agg(Count=('Subscriptions','count')).sort_values(by="Subscriptions", ascending=False).head(10)

df.groupby('Grade').agg(Average_subscriber=('Subscriptions', "mean"))

df[df['Grade'] == 'A++'].sort_values(by='Views', ascending=False).head(5)

