# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1icMD6HeC4iDPgZMnx24yG9yKRla7FNMl
"""

# Import Libraries and datasets
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv("/content/tips2.csv")

# Set Seaborn style
sns.set(style="whitegrid", palette="pastel", font_scale=1.2)

# Create the plot
plt.figure(figsize=(16, 6))
plt.subplot(1, 2, 1)
sns.histplot(df['bill'], kde=True, bins=20, color='skyblue')
plt.title('Distribution of Total Bill')
plt.show()

plt.subplot(1, 2, 2)
sns.histplot(df['tip'], kde=True, bins=20, color='salmon')
plt.title('Distribution of Tip Amount')
plt.tight_layout()
plt.show()

plt.figure(figsize=(16, 8))
categorical_columns = ['gender', 'smoker', 'day', 'time']
for i, col in enumerate(categorical_columns, 1):
 plt.subplot(2, 2, i)
 sns.countplot(x=col, data=df, palette='Set2')
 plt.title(f'Count Plot of {col.capitalize()}')
plt.tight_layout()
plt.show()

#BIVARIATE ANALYSIS
plt.figure(figsize=(8, 6))
sns.scatterplot(x='bill', y='tip', data=df, hue='gender', style='smoker', palette='Set1')
plt.title('Scatterplot of Tip vs. Total Bill')
plt.show()

plt.figure(figsize=(8, 6))
sns.boxplot(x='day', y='tip', data=df, palette='Set3')
plt.title('Boxplot of Tip Amount by Day')
plt.show()

#MULTIVARIATE ANALYSIS
sns.pairplot(df, hue='smoker', diag_kind='kde', palette='husl')
plt.suptitle('Pairplot of Numerical Variables by Smoker Status', y=1.02)
plt.show()

plt.figure(figsize=(8, 6))
# Calculate correlation only for numeric columns
corr_matrix = df.select_dtypes(include=['number']).corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f', square=True)
plt.title('Correlation Heatmap')
plt.show()

