# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import sum

# Step 1: Create a SparkSession
spark = SparkSession.builder \
    .appName("TotalSpentByCustomer") \
    .master("local[*]") \
    .getOrCreate()

# Step 2: Create a DataFrame with sample data
data = [
    ("Alice", 200),
    ("Bob", 150),
    ("Alice", 100),
    ("Bob", 50),
    ("Alice", 300)
]
columns = ["Customer", "Amount"]
df = spark.createDataFrame(data, columns)

# Step 3: Group by Customer and calculate the total amount spent
result_df = df.groupBy("Customer").agg(sum("Amount").alias("TotalSpent"))

# Step 4: Show the result
result_df.show()

# Stop the SparkSession
spark.stop()

